# Clé API pour l'envoi d'e-mails

SENDGRID_API_KEY = "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"



# Adresse e-mail de l'expéditeur (doit être celle que vous avez vérifiée sur SendGrid)

SENDER_EMAIL = "eve.rosenbach@gva.ch"



# Liste des adresses e-mail des destinataires (les analystes OOP)

# Séparez les adresses par une virgule

RECIPIENT_EMAILS = "eve.rosenbach@gva.ch, bruno.benedetti@gva.ch"
